# Generated by Django 5.2.8 on 2025-11-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicine_img/')),
                ('MRP', models.DecimalField(decimal_places=2, max_digits=10)),
                ('formulation', models.CharField(max_length=100)),
                ('ingredients', models.JSONField(blank=True, null=True)),
                ('indications', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
